### PR TITLE
Added metadata fix for gnome-shell versions 3.18, 3.22, and 3.24

### PR DESCRIPTION
**Pull request by davegregg**

### CODE REVIEW

**Comment by bsaleil** [comment]
Did you test it on 3.22 or 3.24 ?

**Comment by davegregg** [comment]
I tested it on 3.24.1. Running it right now -- works great.

**Comment by davegregg** [comment]
Another user had [previously tested 3.22](https://github.com/bsaleil/todolist-gnome-shell-extension/issues/40#issuecomment-260110687)

**Comment by mathbagu** [comment]
Adding "3.22" to metadata.json works well on fedora 25 (gnome-shell version is 3.22.3).

**Comment by bsaleil** [comment]
Thanks.

**Comment by pringlized** [comment]
Just tried to install and it failed. I'm Gnome shell 3.24.2 on Arch 4.11.9-1.

I'm getting the following error. Any suggestions before I pop open the hood and trace it down?

TypeError: redeclaration of formal parameter iter

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:49

**Pull request merged**
